title:        Mez Gebre
email:        mez@jetcode.io
description:  "A scratchpad for projects and ideas from an engineer who loves connecting dots across domains."
author:       Mez Gebre
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
paginate:     5
excerpt_separator: <!-- more -->
twitter_username: mez_gebre
github_username:  mez
disqus_shortname: 'mez-github-io'
url: https://mez.github.io
image_base: /public/img
date_format: '%B %d, %Y'
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]

# SEO settings
twitter:
  username: mez_gebre
  card: summary_large_image
social:
  name: Mez Gebre
  links:
    - https://twitter.com/mez_gebre
    - https://github.com/mez